<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Medicamentos</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-10-31T13:50:40</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4569e87a-304c-400f-b8cf-14e6ec1a5b87</testSuiteGuid>
   <testCaseLink>
      <guid>f864de56-6457-40d6-bad6-d080ebc51a74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Buscar Farmacias - Domicilio</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>688d02d7-d309-4bfa-880e-e88fc195ab2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae747b81-d1f6-4838-b04a-b7f07fec92ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>981d6189-55a5-4154-88b6-ffffdafe4183</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50b150b6-8c86-4dbd-9de7-94db6bb152a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a832dde-863c-4ad5-a85a-ec80d1bc427d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3763f2e-052e-42e4-acf2-c1763035b17e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d57b559-4638-4002-90f8-96b4ea7b6e06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe796a80-eb71-4368-9002-d3a71927baa5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60ab5739-8ba5-4ca1-9967-e9b17dce2922</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Buscar Farmacias - Zona</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a6fb2ba-0f12-4ea4-a921-b858c80df608</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d19541dc-40ec-4469-8cbe-045995c8e26f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8181bfc9-8991-46cc-9a07-0dd45ab8e478</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf137006-8d71-4f55-99b1-20d879df5456</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>463f992f-043b-49f2-835b-2fbf94ba2bf7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c7fe35b-394d-452f-946a-51b6dfb21811</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
