<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Prestaciones</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-02T11:49:12</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3c8a1e11-ba17-4a00-b3e2-99e94ece3aad</testSuiteGuid>
   <testCaseLink>
      <guid>7ca08a67-a3d7-4c34-9f07-576ae1464712</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Buscar Prestadores - Domicilio</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2b0bd11-7bc4-485e-828d-14e3d23f26b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bdfa6f9-c9d1-40bb-a10a-0c29763e9207</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d64d447-9d54-49fa-bbc4-89392be78582</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18119fb0-87d2-40af-880f-d70bbc09667d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c893205c-fc2f-43b8-af0b-e37a800e59da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6b8f2e2-b89e-4e55-97df-030130f7b64a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3619953c-60ef-44f6-b439-f774059134e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d05fafd-c08f-4c3e-a7bd-07a4264a12fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f601133-8f95-4718-97c5-7109f596c4df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37c01a3a-139b-4b2e-bebe-515d41a8241e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Buscar Prestadores - Zona</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe2007ed-3fc0-4944-ac09-cba0d4524510</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c94849b-5f40-4051-a875-3b5eca25578c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53504618-fa8c-4cb6-9ac4-44d1cec09ce5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1c6cf80-a181-41d5-95a7-62886f13e6c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d821392-3531-4f78-975a-a711b08bb80c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea387061-4165-4073-9388-3c9d2186bc84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>394317c5-7a5c-41d3-b363-a27e9ee1ea82</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67ed5116-38f0-4e2f-99ad-a42917f0ea59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Buscar Prestadores - Prestador</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bea1d03-adf1-4755-bfd7-15c0b0a2b899</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25e68a50-793e-42e4-baf7-07c9705f6488</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efeebafa-c72c-45dd-8867-7afe54b1a4bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98c35fa9-3ccc-41bd-aa55-99dfb3b0285a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc7dba1e-9e2c-4a92-bebf-74b2c7b33beb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4560e2a-9cfb-4653-b807-9674d89eea63</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
