<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Prestaciones</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-10-19T14:46:23</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3c8a1e11-ba17-4a00-b3e2-99e94ece3aad</testSuiteGuid>
   <testCaseLink>
      <guid>7ca08a67-a3d7-4c34-9f07-576ae1464712</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Buscar Prestadores - Domicilio</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2b0bd11-7bc4-485e-828d-14e3d23f26b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bdfa6f9-c9d1-40bb-a10a-0c29763e9207</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d64d447-9d54-49fa-bbc4-89392be78582</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18119fb0-87d2-40af-880f-d70bbc09667d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c893205c-fc2f-43b8-af0b-e37a800e59da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6b8f2e2-b89e-4e55-97df-030130f7b64a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3619953c-60ef-44f6-b439-f774059134e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d05fafd-c08f-4c3e-a7bd-07a4264a12fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f601133-8f95-4718-97c5-7109f596c4df</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
